### ISSUE TITLE
Implement support for aggregated discovery

### ISSUE THREAD

**Issue by taotriad** [intel/cluster-management-toolkit#15]
Since we offer support for a lot of different APIs, and attempt discovery for all of them on startup there can be quite a lot of network requests in a complex setup.

Kubernetes 1.26 introduces the concept of aggregated discovery (feature gate enabled in Kubernetes 1.27); it minimises the network traffic, and would thus be a great thing to implement. See the following link for more info.

[Aggregated Discovery](https://sysdig.com/blog/kubernetes-1-27-whats-new/#3352)

**Comment by dweineha** [comment]
This has now been implemented and seems to work properly.
