### ISSUE TITLE
Kubernetes package repositories have moved and changed behaviour

### ISSUE THREAD

**Issue by dweineha** [intel/cluster-management-toolkit#18]
Kubernetes packages are now built and distributed through OBS. This means two things: first of all the URLs have changed (easy to accommodate for). Second of all each minor release has its own URL, meaning that we need some means of finding out what the latest release is, and add repo files for all repositories from the first supported to the latest supported to ensure feature parity with the current behaviour.

cmtadm cv should check if there are new upstream minor versions available, and run playbooks/add_kubernetes_repo.yaml if necessary. cmt should also have a refresh-repos command that unconditionally runs playbooks/add_kubernetes_repo.yaml, to handle cases where repository keys have been renewed.

**Comment by taotriad** [comment]
This was fixed for Debian/Ubuntu in commit 87ea2c92490d6ed43741a6b07629e9f348472732.
For RHEL etc. this still remains TBD.

**Comment by dweineha** [comment]
This has now been fixed in cmtadm for Red Hat derivatives too.
