### ISSUE TITLE
The helptext generator doesn't work properly for the list view

### ISSUE THREAD

**Issue by taotriad** [intel/cluster-management-toolkit#20]
The built-in shortcuts shows up twice in some cases.

Rather than fix the old implementation we should rewrite the code to use generic_inputhandler() + generate_helptext() from curses_helper.

**Comment by taotriad** [comment]
This can be reproduced by opening a list view that makes use of the view yaml & view json shortcuts. Reopen the same view again and those entries will be duplicated.

**Comment by taotriad** [comment]
This is fixed in 6ef3c8354c6ce3c80a437b373d9e62c92aab5e55 in the systempath branch.

**Comment by dweineha** [comment]
The systempath branch has now been merged.
