### ISSUE TITLE
Architect and implement proper asynchronous data-handling for views

### ISSUE THREAD

**Issue by taotriad** [intel/cluster-management-toolkit#7]
Currently only the inventory view, the cluster overview, and the context view has some form of asynchronous behaviour, with varying degrees of functionality (the context view seems to be semi-broken).

Architect a proper way of doing this.

Requirements:
* Rate limiting to ensure that the control plane (or the local machine!) isn't overloaded
* Pause updates either through manual toggle, or whenever an update would trigger a resort of the list, the user is moving, or there are selected items
* For the log parser the updates & rendering needs to be progressive

**Comment by dweineha** [comment]
This is now WIP, with the cluster overview being the first construction area.

**Comment by taotriad** [comment]
The asynchronous branch has now been merged. Closing this.
